server:
  port: 9407

spring:
  application:
    name: xypai-common
  profiles:
    active: @profiles.active@

# Dubbo配置
dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  protocol:
    name: dubbo
    port: 20807  # Dubbo端口 (HTTP端口9407 + 11400)
  registry:
    address: nacos://${nacos.server-addr}
    group: ${nacos.discovery.group:DUBBO_GROUP}
  scan:
    base-packages: org.dromara.common.**.dubbo  # 扫描Dubbo服务实现类
  consumer:
    check: false  # 启动时不检查依赖的服务
    timeout: 3000  # 调用超时时间(ms)
  provider:
    timeout: 5000  # 服务端超时时间(ms)
